#+LATEX_CLASS: achemso
#+LATEX_CLASS_OPTIONS: [journal=nalefd,manuscript=letter,email=true,hyperref=true,keywords=true]
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{times}

#+OPTIONS: tex:t toc:nil todo:t author:nil date:nil title:nil ^:t tags:nil
#+DESCRIPTION:
#+TITLE: An elastic interfacial transistor enabled by superhydrophobicity
#+LATEX_HEADER: \author{Tian Tian}
#+LATEX_HEADER: \affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir-Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}
#+LATEX_HEADER: \author{Chander Shekhar Sharma}
#+LATEX_HEADER: \altaffiliation{Present address: Department of Mechanical Engineering, Indian Institute of Technology Ropar, Rupnagar, Punjab 140001, India}
#+LATEX_HEADER: \affiliation{Laboratory of Thermodynamics in Emerging Technologies, Department of Mechanical and Process Engineering, ETH Z{\"{u}}rich, Sonneggstrasse 3, CH-8092 Z{\"{u}}rich, Switzerland}
#+LATEX_HEADER: \author{Navanshu Ahuja}
#+LATEX_HEADER: \affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir-Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}
#+LATEX_HEADER: \author{Matija Varga}
#+LATEX_HEADER: \affiliation{Electronics Laboratory, ETH Z{\"{u}}rich,  Gloriastrasse 35,  CH-8092 Z{\"{u}}rich, Switzerland}
#+LATEX_HEADER: \author{Raja Selvakumar}
#+LATEX_HEADER: \altaffiliation{Present address: Department of Chemical and Biomolecular Engineering, University of California, Berkeley, CA 94720, USA}
#+LATEX_HEADER: \affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir-Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}
#+LATEX_HEADER: \author{Yen-Ting Lee}
#+LATEX_HEADER: \affiliation{Department of Chemical Engineering, National Taiwan University of Science and Technology, Taipei 10607, Taiwan.}
#+LATEX_HEADER: \alsoaffiliation{National Synchrotron Radiation Research Center, Hsinchu 30076, Taiwan.}
#+LATEX_HEADER: \author{Yu-Cheng Chiu}
#+LATEX_HEADER: \affiliation{Department of Chemical Engineering, National Taiwan University of Science and Technology, Taipei 10607, Taiwan.}
#+LATEX_HEADER: \author{Chih-Jen Shih}
#+LATEX_HEADER:\email{chih-jen.shih@chem.ethz.ch}
#+LATEX_HEADER: \affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir-Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}

#+LATEX_HEADER: \keywords{Interfacial field-effect transistor, two-dimensional materials, liquid metal, stress sensing, wetting, semiconductor nanowires, multiscale phenomena}


#+NAME: abstract
  #+BEGIN_EXPORT latex
\newpage{}
\begin{abstract}
  % Having been the central component of the semiconductor industry for
  % more than 70 years, the field-effect transistors (FETs) still
  % attract substantial interest and development. One long-existing
  % challenge is to incorporate mechanical responsiveness and durability
  % into FETs, which requires tedious material design and may compromise
  % device performance. Here we introduce an alternative approach, the
  % interfacial field-effect transistor (IFET), combining multiscale
  % interfacial physical phenomena, to address such problem. The
  % mechanical responsiveness of IFET is harnessed from a conductive
  % Cassie-Baxter sessile droplet on superhydrophobic semiconducting
  % nanowires, formed by templated growth on the interface of a
  % two-dimensional electron gas (2DEG). The extremely low elastic
  % modulus of the droplet, much lower
  % than any existing rubbers, ensures an excellent elastic sensiting
  % limit down to \textless{}10 Pa. The partial penetration of electric field
  % through the 2DEG modulates the carrier profile at the NW/2DEG
  % interface and a thermal-tunable current on/off ratio exceeding
  % $3\times{}10^{4}$. This study demonstrates a versatile platform that
  % bridges multiple macroscopic interfacial phenomena with
  % nanoelectronic responses, which can be used to facilely extend the
  % functionality of semiconductor components.
  Enabling mechanical responsiveness in field-effect transistors
  (FETs) offers new technological opportunity beyond the reach of
  existing platforms. Here we propose a new force-sensing concept by
  controlling the wettability of a semiconductor surface, referring to
  the interfacial field-effect transistors (IFETs). We design an IFET
  made by superhydrophobic semiconductor nanowires (NWs) sandwiched
  between a layer of two-dimensional electron gas (2DEG) and a
  conductive Cassie-Baxter (CB) sessile droplet. Following the
  hydrostatic deformation of the CB droplet upon mechanical stress, we
  report an extremely small elastic modulus of 820 pascals vertical to
  the substrate plane, or $\sim{}$100 times softer than Ecoflex rubbers,
  enabling an excellent stress detection limit down to \textless{}10
  pascals and a stress sensitivity of 36 kPa$^{-1}$. The IFET exhibits
  an on/off current ratio exceeding $3\times{}10^{4}$, as the carrier
  density profile at the NW/2DEG interface is modulated by a
  partially-penetrated electrostatic field. This study demonstrates a
  versatile platform that bridges multiple macroscopic interfacial
  phenomena with nanoelectronic responses.
\end{abstract}
  #+END_EXPORT

#+NAME: TOC
#+BEGIN_EXPORT latex
% \begin{tocentry}
%   \vfill
%   \includegraphics[width=0.98\linewidth]{raw_img/TOC.pdf}
%   \vfill
% \end{tocentry}
#+END_EXPORT

* Abstract                                                           :ignore:
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
\newpage{} Recent advances in semiconductor materials and physics have
driven the development of field-effect transistors (FETs) for a
variety of applications cite:Torsi_2013_rev,Ben_Sasson_2014.  Enabling
mechanical durability and responsiveness in FETs offers new
technological opportunities beyond the reach of existing platforms
cite:Someya_2004,Oh_2016,Shin_2017. It is desirable to intrinsically
incorporate the responsiveness in semiconductor by rational materials
design cite:Oh_2016 but often compromises the device performance and
processability cite:Lee_2018. For example, the elasticity, the ability
of a soft material to return to its original shape when the deforming
stress is released, requires an entropic force acting within the
material, fundamentally impeding carrier transport
cite:OConnor_2011_strain_P3HT. As a result, so far there are only few
reports that have successfully demonstrated stress-sensing FETs using
intrinsically flexible semiconductors cite:Oh_2016. On the other hand,
incorporating transistor components into a mechanically flexible
matrix also offers opportunities for stress-sensing FETs. A widely
used strategy involves conductive elastic polymer as the
pressure-sensitive unit
cite:Someya_2004,Sekitani_2009,Kaltenbrunner_2013,Takei_2010, of which
the sensitivity is limited by the properties of the polymer-based
components. Microstructures embedded in an elastomer enhances the
mechanical durability cite:Jang_2015, and can be used to improve the
flexibility and responsiveness of flexible rubber-based FETs
cite:Mannsfeld_2010,Schwartz_2013. Recently, highly sensitive FETs
using air as the compressible dielectric layer has as also been
proposed cite:Zang_2015,Shin_2017. The elasticity of the polymer-based
FETs essentially depends on the elastic modulus of the flexible
material, which is typically in the range of $10^{1}\sim{}10^{3}$ kPa
cite:Amjadi_2016. Here we present a conceptually
different approach, referring to the interfacial field-effect
transistor (IFET), in which the mechanical responsiveness is
controlled by the wettability of a semiconductor surface.

* Main                                                               :ignore:
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

Figure [[ref:fig:main-1]] presents the device architecture of the proposed
IFET. We consider a quantum capacitor device cite:Luryi_1988, in which
a semiconductor layer is sandwiched between a conductive drain (D) and
a 2DEG source (S) electrodes. The ultrathin and
low-quantum-capacitance (low $C_{\mathrm{Q}}$) nature of 2DEG allows
partial penetration of an electrostatic field exerted by the
underlying gate (G) electrode cite:Shih2015Partially,Tian_2016,
modulating the carrier density in semiconductor that controls
drain-to-source current (\(I_{\mathrm{DS}}\)) (Figure
[[ref:fig:main-1]]a).  In addition, the fact that $I_{\mathrm{DS}}$
passes through two semiconductor-electrode interfaces maximizes the
response to the interfacial properties.

Next, we sought to grow semiconductor NWs directly on the 2DEG,
forming a superhydrophobic surface at the Cassie-Baxter (CB) state
cite:Cassie_1944. A conductive sessile droplet is then placed on top
of the NWs, acting as the D electrode, with the radius of contact,
$R$. Accordingly, applying a compressive stress $\sigma$ on top
of the sessile leads to a horizontal displacement $\Delta x$ that
advances the contact line, with an apparent advancing contact angle
$\theta_{\mathrm{adv}}^{*}$ (Figure [[ref:fig:main-1]]b left). When the
stress is released, the contact line moves back towards its
equilibrium shape, with an apparent receding contact angel of
$\theta_{\mathrm{rec}}^{*}$ (Figure [[ref:fig:main-1]]b right), enabling the
reversibility. We hypothesized that the electrical response during the
process results from: (i) an increase of the droplet contact area
$\Delta A \approx 2 \pi R \Delta x$ at the macroscopic level and (ii)
an increase of penetration length $\Delta l \approx \sigma
r^{2}/2\gamma_{\mathrm{L}}$ that effectively reduces the semiconductor
channel length in the NWs (see Figure  [[ref:fig:main-1]]b bottom), where
$\gamma_{\mathrm{L}}$ is the surface tension of liquid and $r$ is the
average radius between NWs.  In order to realize the concept,
monolayer graphene (Gr), a 2DEG material with the smallest quantum
capacitance near the Dirac point cite:Tian_2016, is used. As for the
semiconductor material, it is well-known that the covalently bonded
semiconductors generally possess a high surface energy, owing to the
high surface polarity cite:Azimi_2013_wetting_RO and dangling bonds
cite:Zhang_2004_dangling, presumably leading to the Wenzel state. To
this end, the organic semiconductor solids containing the
\(\pi\)-conjugated molecules, with the molecular polarizability
considerably reduced by perfluoration, were considered. We have
managed to grow NWs of Copper(II) hexadecafluorophthalocyanine
(F_{16}CuPc), a n-type organic semiconductor with high air stability
cite:Bao_1998, on a sheet of monolayer graphene transferred onto a
SiO_{2}/Si substrate (details see Section S1 and 
Figure S2 in the Supporting Information), as shown in Figure [[ref:fig:main-2]]a.

The F_{16}CuPc NWs have high aspect ratios, with diameters and heights
of 30 - 60 and several hundred nanometers, respectively. We notice that
the NW morphology is similar to the F_{16}CuPc films templated by
perylene-3,4,9,10-tetracarboxylic-3,4,9,10-dianhydride (PTCDA)
cite:Yang_2009_F16_PTCDA or gold nanoparticles
cite:Mbenkum_2006_F16_1D, presumably sharing the same growth
mechanism. Indeed, the strong $\pi-\pi$ interactions between graphene
and F_{16}CuPc basal planes lower the critical free energy of
heterogeneous nucleation; in combination with the weak van der Waals
(vdW) interactions between the perfluorinated molecular edges that
limit the lateral growth, it explains why the NW structure is
thermodynamically favored. The structural driving force resulting from
the subtle asymmetry between in-plane and out-of-plane interactions,
however, disappears when the substrate-molecule interactions are not
sufficiently strong cite:Tian_2017, as observed in the thin-film
structure grown on bare SiO_{2} (Figure [[ref:fig:main-2]]a). More analysis
about the morphologies of F_{16}CuPc NW and F_{16}CuPc/SiO_{2} samples
see Section S2 and Figures S3-S9 in the Supporting Information.

Figure [[ref:fig:main-2]]b shows the grazing incidence X-ray diffraction
(GIXD) patterns for the F_{16}CuPc NW and F_{16}CuPc/SiO_{2}
samples. The F_{16}CuPc/SiO_{2} sample has an intense peak along the
$q_{\mathrm{z}}$ axis, labeled as $\alpha$ (/d/-spacing = 1.470
nm). It corresponds to the (002) plane in the F_{16}CuPc single
crystal cite:Yang_2009_F16_PTCDA that is perpendicular to the
substrate normal vector, suggesting a dominant "edge-on" orientation
(Figure [[ref:fig:main-2]]b bottom left). It is also endorsed by the
position of the (\(\bar{1}\)22) plane peak near the $q_{\mathrm{xy}}$
axis (\(\beta\)) cite:Yoon_2010_crystal_F16, with a /d/-spacing of
0.305 nm. On the other hand, for the F_{16}CuPc NW sample, we observe
an additional peak corresponding to the (002) plane (labeled as
$\gamma$) (Figure [[ref:fig:main-2]]b right), with its wave vector rotated
by $\sim 76^{\circ}$ with respect to the $q_{\mathrm{z}}$ axis and a
/d/-spacing of 1.440 nm, slightly smaller than that in the edge-on
orientation. Together with the (\(\bar{1}\)22) peak located at the
$q_{\mathrm{z}}$ axis, we point out the emergence of the "face-on"
orientation (Figure [[ref:fig:main-2]]b bottom right) in the NWs. The
orientations revealed by GIXD patterns are in consistent with X-ray
diffraction (XRD) experiments (details see Section S2, Figure S10 and
Table S1 in the Supporting Information). The predominant face-on
orientation in the n-type NWs facilitates electron transport
perpendicular to the substrate, through the intermolecular $\pi-\pi$
interactions. The substrate-induced orientation transition also
results in the angle-dependent scattering of the Davydov multiplets
that alters the Raman characteristics cite:Cerdeira_2013_RamanF16
(details see Figure S11, Supporting Information). Figure
[[ref:fig:main-2]]c presents the scanning electron microscopy (SEM)
micrograph and Raman map giving the intensity ratio of the peak at
1380 cm^{-1} to that at 1315 cm^{-1}, I(1380)/I(1315), on the
F_{16}CuPc film deposited on a sheet of SiO_{2}-supported graphene
with a break. The NW region, with a higher I(1380)/I(1315) ratio, is
clearly identified.

We examined the wettability of the two F_{16}CuPc samples (Figures
[[ref:fig:main-2]]d-[[ref:fig:main-2]]g). The apparent static contact
angles (\(\theta_{\mathrm{s}}^{*}\)) of water were independently
determined by (i) a contact angle goniometer (CAG) and (ii) condensation
of  water vapor in an environmental scanning electron
microscope (ESEM) setup. For example, Figure [[ref:fig:main-2]]d
presents the CAG/ESEM-measured $\theta_{\mathrm{s}}^{*}$ of a 50 nm-thick
F_{16}CuPc/SiO_{2} and a 300 nm-thick F_{16}CuPc NW samples, showing
103.0\(\pm\)5.4\(^{\circ}\) / 107.0\(\pm\)3.9\(^{\circ}\) and
152.8\(\pm\)3.9\(^{\circ}\) / 149.8\(\pm\)3.4\(^{\circ}\),
respectively. To gain more insights into the superhydrophobic states
of the two surfaces, we conducted a series of static and dynamic
contact angle measurements which allow us to determine
$\theta_{\mathrm{adv}}^{*}$, $\theta_{\mathrm{rec}}^{*}$ and
$\theta_{\mathrm{s}}^{*}$, with respect to the film thickness (Figure
[[ref:fig:main-2]]e). The apparent contact angle values
$\theta_{\mathrm{i}}^{*}$, where i=adv, rec, and s, were numerically
fitted by the Wenzel (W) cite:Wenzel_1936 and CB cite:Cassie_1944
models, given by (details see Supplementary Section S3):

\begin{eqnarray}
\label{eq:2}
&\cos \theta^{*}_{\mathrm{i,W}} =& r_{\mathrm{W}} \cos \theta_{\mathrm{i}} \\
&\cos \theta^{*}_{\mathrm{i,CB}} =& r_{\mathrm{CB}} f \cos \theta_{\mathrm{i}} + f - 1
\end{eqnarray}
 where $r_{\mathrm{W}}$ and $r_{\mathrm{CB}}$ are the roughness ratio
 of the wet surface area in the two (W and CB) states,
 $\theta_{\mathrm{i}}$ is the respective contact angles on an ideal
 surface and $f$ is the fraction of solid surface area wet by water in
 the CB model. By assuming $r_{\mathrm{W}} \approx r_{\mathrm{CB}}$
 that linearly increases with film thickness owing to the
 intrinsically identical chemical nature of the two surfaces, we find
 that the water wettability on F_{16}CuPc/SiO_{2} and F_{16}CuPc NW
 samples can be nicely described by the Wenzel and CB models,
 respectively (solid lines in Figure [[ref:fig:main-2]]e), allowing us to
 determine \(\theta_{\mathrm{adv}}\)=107\(^{\circ}\),
 \(\theta_{\mathrm{rec}}\)=78\(^{\circ}\),
 \(\theta_{\mathrm{s}}\)=94\(^{\circ}\), and /f/ =0.093 (for 300 nm
 NWs) (details see Table S2, Supporting Information).  Although some discrepancy
 can be seen between the experimental and model data, the simple CB
 and Wenzel models still nicely capture the distinct wetting behaviors
 on the two F_{16}CuPc morphologies. We point out that the
 graphene-induced molecular orientation effects have eventually led to
 the transition between Wenzel and CB states, which to our knowledge
 has never been demonstrated in molecular solids.

 We next illustrate the wettability of conductive sessile droplets,
 specifically the liquid metals (LMs) at room temperature on the
 F_{16}CuPc samples. It is noteworthy that the key challenge hindering
 the development of LM-based devices is the undesirable adhesion of LM
 to the device surface, in particular with the eutectic gallium indium
 (EGaIn), in which the formation of gallium oxide layer effectively
 reduces the interfacial tension
 cite:Dickey_2008,Doudrick_2014_oxide. Mercury sessile droplets
 sitting on the F_{16}CuPc/SiO_{2} and F_{16}CuPc NW surfaces show
 $\theta_{\mathrm{s}}^{*}$ values of 147.7\(\pm\)2.5\(^{\circ}\) and
 157.1\(\pm\)3.8\(^{\circ}\), respectively(Figure [[ref:fig:main-2]]f).
 Regarding the EGaIn sessile droplets, although the
 $\theta_{\mathrm{s}}^{*}$ values of fresh droplets are close on both
 surfaces, interestingly, the adhesive property is significantly
 different, as revealed in Figure [[ref:fig:main-2]]g. We suspended an EGaIn
 droplet using a microcapillary, followed by repeatedly
 touching/removing the droplet from the two surfaces. We found that
 the EGaIn droplet can be easily detached from the F_{16}CuPc NW
 surface (Figure [[ref:fig:main-2]]g right), compared to that stuck to the F_{16}CuPc/SiO_{2} 
 surface Although some discrepancy
 can be seen between the experimental and model data, the simple CB
 and Wenzel models still nicely capture the distinct wetting behaviors
 on the two F_{16}CuPc morphologies. We point out that the
 graphene-induced molecular orientation effects have eventually led to
 the transition between Wenzel and CB states, which to our knowledge
 has never been demonstrated in molecular solids.

 We next illustrate the wettability of conductive sessile droplets,
 specifically the liquid metals (LMs) at room temperature on the
 F_{16}CuPc samples. It is noteworthy that the key challenge hindering
 the development of LM-based devices is the undesirable adhesion of LM
 to the device surface, in particular with the eutectic gallium indium
 (EGaIn), in which the formation of gallium oxide layer effectively
 reduces the interfacial tension
 cite:Dickey_2008,Doudrick_2014_oxide. Mercury sessile droplets
 sitting on the F_{16}CuPc/SiO_{2} and F_{16}CuPc NW surfaces show
 $\theta_{\mathrm{s}}^{*}$ values of 147.7\(\pm\)2.5\(^{\circ}\) and
 157.1\(\pm\)3.8\(^{\circ}\), respectively(Figure [[ref:fig:main-2]]f).
 Regarding the EGaIn sessile droplets, although the
 $\theta_{\mathrm{s}}^{*}$ values of fresh droplets are close on both
 surfaces, interestingly, the adhesive property is significantly
 different, as revealed in Figure [[ref:fig:main-2]]g. We suspended an
 EGaIn droplet using a microcapillary, followed by repeatedly
 touching/removing the droplet from the two surfaces. We found that
 the EGaIn droplet can be easily detached from the F_{16}CuPc NW
 surface (Figure [[ref:fig:main-2]]g left). The observation was further
 corroborated by their apparent sliding angles
 $\theta_{\mathrm{sl}}^{*}$, equivalent to the degree of contact angle
 hysteresis, of 56.1\(\pm\)13.2\(^{\circ}\) and
 14.6\(\pm\)2.6\(^{\circ}\) on F_{16}CuPc/SiO_{2} and F_{16}CuPc NW
 samples, respectively (details see Supplementary Table
 S3). Accordingly, the excellent CB characteristics of LM sessile
 droplets on the semiconducting NWs form a solid basis for the
 proposed elastic IFET.

 Figure [[ref:fig:main-3]]a presents the schematic of the proposed elastic
 IFET. A sheet of monolayer graphene grown by chemical vapor
 deposition (CVD) was transferred onto a 300 nm SiO_{2}/Si substrate
 functionalized by octadecyltrichrolosilane self-assembled monolayer
 (OTS SAM) cite:Yan_2011, in order to minimize the substrate-induced
 traps cite:Wang_2011.  The lateral graphene FET has an on/off current
 ratio of \sim{}10 and a field-effect mobility (\(\mu_{\mathrm{FE}}\))
 of \sim2000 cm^{2}V^{-1}s^{-1} at room temperature, with the charge
 neutrality point (CNP) at the gate voltage of \sim0 V (Figure S14,
 Supporting Information). Subsequently, a layer of \sim300 nm-high
 F_{16}CuPc NWs was deposited on graphene, followed by placing a
 cantilever-attached LM droplet on top as the D electrode (details see
 Section S1, Supporting Information).  The current density
 $J_{\mathrm{DS}}$ from the LM (D) to graphene (S) in the IFET was
 then quantified by normalizing the drain current by the contact area
 of the sessile droplet with the NW layer, such that $J_{\mathrm{DS}}
 = {\displaystyle \frac{I_{\mathrm{DS}}}{\pi R^{2}}}$, where $R$ is
 determined from the CAG optical micrograph of the LM droplet (Figure
 [[ref:fig:main-3]]a inset), as a function of drain and gate voltages
 ($V_{\mathrm{D}}$ and $V_{\mathrm{G}}$). Note that since the NWs are
 only partially wetted, the actual current density passing through
 individual NWs is estimated to be $J_{\mathrm{DS}}/f$. The carrier
 density in the F_{16}CuPc molecules adjacent to the NW/Gr interface
 is modulated by the partially penetrated field effect through
 monolayer graphene cite:Tian_2016,Shih2015Partially, modulating the
 Schottky barrier height at the interface cite:Yang2012Barristor. The
 face-on orientation of the F_{16}CuPc molecules also facilitates
 interfacial carrier transport in two ways. The overlap between $\pi$
 orbitals of F_{16}CuPc molecules along the face-on stacking direction
 ensures high carrier mobility in the NWs cite:Bao_1998. Moreover, the
 work function of face-on F_{16}CuPc molecules aligns with graphene,
 compared with large work function mismatch between edge-on F_{16}CuPc
 and graphene cite:Mao_2010_F16_level_orien,Ren_2011_F16Gr_Elevel. At
 zero strain corresponding to the droplet height at $H_{0}$ determined
 analytically (see eq [[ref:eq:H0]], as will be discussed later), the
 transfer curve for a representative IFET at \(V_{\mathrm{D}}\)= 1 V
 demonstrates an on/off current ratio of 3.9\(\times\)10^{4} (Figure
 [[ref:fig:main-3]]b), in line with the state-of-the-art vertical
 field-effect transistor (VFET) technology
 cite:Yang2012Barristor,Shih2015Partially,Sun_2017_COF_VFET,Ben_Sasson_2011. Moreover,
 the fact that the present IFET is well-functional at a low
 $V_{\mathrm{D}}$ reflects it potential towards the low-power
 electronics design, which remains challenging for most resistive
 force-sensing components cite:Pan_2014,Pang_2012. A number of IFET
 samples were characterized, showing an average on/off current ratio
 of 5\(\times\)10^{3} at \(V_{\mathrm{D}}\)=1 V (Figure
 [[ref:fig:main-3]]b inset). The transfer curves at different
 $V_{\mathrm{D}}$ are shown in Figure [[ref:fig:main-3]]c, with the on/off
 current ratio gradually decreases with $V_{\mathrm{D}}$, owing to a
 mechanism analogous to the drain-induced barrier lowering (DIBL)
 effect in short-channel FETs cite:Lundstrom_2003. We note the slight
 difference each device may be caused by the air-borne doping of the
 IFET, and further efforts will be made to improve the repeatability
 of such devices. More discussions about the transport mechanisms,
 together with the band diagrams, are stated in Section S4, Figures
 S12, S15-S19 in the Supporting Information. Three-terminal operation
 of the IFET offers integrated device functionalities sharing with
 typical FETs. We demonstrate a circuit composed by an IFET, a green
 light-emitting diode (LED), and a bipolar junction transistor (BJT)
 amplifier (circuit schematic see Figure [[ref:fig:main-3]]d left), with
 the contact angle monitored by a CAG (Figure [[ref:fig:main-3]]d
 middle). Through continuous forward-reverse scan of $V_{\mathrm{G}}$,
 the total current $I_{\mathrm{tot}}$ that passes through the circuit,
 is modulated by \sim250 folds and switches the LED on and off,
 showing a high current stability and reproducibility (Figure
 [[ref:fig:main-3]]d right). The circuit design maximized the LED response
 to compressive stress as well (Movies S1 and S2, Supporting Information), as
 will be discussed later.

 The reversible mechanical response of a CB droplet is the key
 principle behind the IFET. To model the elastic response for a CB
 droplet, we consider a droplet sandwiched between two flat plates,
 with two apparent contact angles $\theta_{\mathrm{t}}^{*}$ and
 $\theta_{\mathrm{b}}^{*}$, corresponding to the top and bottom
 liquid-solid interfaces, respectively. Under the assumptions of (i)
 the Bond number Bo\(\ll\)1 and (ii) the contact angles remain
 constant independent of \sigma, the cross-sectional boundary of the
 droplet can be described as a segment of a perfect circle
 cite:berthier_2012_microdroplet. Accordingly, the Laplace pressure
 $p$ of the droplet is given by: \(p = \gamma_{\mathrm{L}}
 (R_{1}^{-1} + R_{2}^{-1})\), where $R_{1}$ and $R_{2}$ are the
 principal radii of the droplet, as schematically shown in Figure
 [[ref:fig:main-4]]a. Upon applying a compressive stress $\sigma$ between
 the plates, the droplet experiences an uniaxial strain $\varepsilon =
 (H_{0} - H) / H_{0}$, where $H_{0}$ and $H$ are the droplet heights
 before and after stress, respectively. The compressive stress varies
 with height, following $\sigma = p(H) - p(H_{0})$. Note that here the
 liquid phase itself is nearly incompressible, and the "elasticity" is
 originated from a thermodynamic driving force counteracting the
 increase of interfacial tension upon mechanical stress, conceptually
 different from the deformation of a bulk material. We formulate the
 principal radii as a function of droplet height $H$ for $H < H_{0}$,
 namely $R_{1}(H)$ and $R_{2}(H)$ (detailed derivations see Section S4
 and Figure S20 in the Supporting Information). First, the maximum
 height $H_{0}$ corresponding to $\sigma=0$ is given by:

  \begin{equation}
  \label{eq:H0}
  \begin{aligned}
    H_{0} &= \sqrt[3]{\frac{3 V_{\mathrm{drop}}}{4 \pi}} \sqrt[3]{\frac{1}{ 
   g(\theta_{\mathrm{t}}^{*}) + g(\theta_{\mathrm{b}}^{*}) -1 }}  \left(\cos \theta_{\mathrm{t}}^{*} + \cos \theta_{\mathrm{b}}^{*
}\right) \\
    g(\theta) &= \left(\frac{1 + \cos \theta}{2} \right)^{2} \left(2 - \cos \theta \right)
  \end{aligned}
  \end{equation}
  where $V_{\mathrm{drop}}$ is the the droplet volume following
  $V_{\mathrm{drop}} = w(R_{1}, H, \theta_{\mathrm{t}}^{*},
  \theta_{\mathrm{b}}^{*})$, in which $w$ is an implicit function of
  $R_{1}$ (see Section S5, Supporting Information) that can be solved
  numerically for a given $H$. On the other hand, the second principal
  radius is geometrically given by:
  \begin{equation}
  \label{eq:1}
  R_{2} = -\frac{H}{\cos \theta_{\mathrm{t}}^{*} + \cos \theta_{\mathrm{b}}^{*}}
  \end{equation}
  By using the above equations, the compressive stress $\sigma$ as a
  function of $\varepsilon$, as well as the effective elastic modulus
  $E = \left({\displaystyle \frac{\mathrm{d} \sigma}{\mathrm{d}
  \varepsilon}}\right)_{H_{0}}$, can be calculated numerically. We
  note that $\theta^{*}_{\mathrm{b}}$ depend on the factor $f$, rather
  than the average radius of the NWs.  To validate our model, a
  mercury droplet having an air-stable surface tension
  \(\gamma_{\mathrm{L}}\)=0.487 J\(\cdot\)m^{-2} is used. Note that
  mercury often forms alloys with commonly-used metals
  cite:Kieffer_1959, so the top contact angle
  $\theta_{\mathrm{t}}^{*}$ may vary depending on the sample
  preparation process. For each droplet height, we determined the
  experimental $\sigma$ by extracting the principal radii from the CAG
  images, with the height controlled by a stage
  micromanipulator. Figure [[ref:fig:main-4]]b compares the experimental
  and calculated elastic stress of a 0.1 \(\mathrm{\mu}\)L droplet as
  a function of strain, showing excellent agreement. We notice that
  within the strain range considered here (up to 13.5%), the $\sigma -
  \varepsilon$ profile is nearly linear, following the Hooke's law. We
  determine the effective elastic modulus to be 820 Pa, which is more
  than 100 times softer than the widely used Ecoflex rubbers
  (\(E\sim{}\)0.1 MPa) cite:Mosadegh_2014, and to our knowledge, softer than any solid
  materials including the state-of-the-art ultrasoft elastomers
  cite:Miriyev_2017,Jang_2015. Using our model, we further calculate
  $E$ versus $V_{\mathrm{drop}}$ (Figure [[ref:fig:main-4]]b inset,
  Figure S22, Supporting Information), predicting an adjustable elastic modulus
  by simply controlling the droplet volume. Unsurprisingly, a smaller
  droplet tends to be stiffer due to an intrinsically large Laplace
  pressure. Another degree of freedom for tunning the elastic modulus
  is the bottom contact angle (Figure S23, Supporting Information); in other
  words, through controlling the wettability of a semiconductor
  surface, one may design an IFET with a desirable mechanical
  responsiveness.

  We next examine the current response of the IFET under mechanical
  stress. Figure [[ref:fig:main-4]]c presents the transfer curves at
  different $\sigma$ values. The current from drain to source
  increases with $\sigma$, with the on/off current ratio unaffected by
  the elastic stress. The elastic response at \(V_{\mathrm{G}}\)= 0 V
  shows a sensitivity, \(\eta = (I/I_{0} - 1) / \sigma\) , where
  \(I_{0}\) and \(I\) are \(I_{\mathrm{DS}}\) before and after stress,
  of 36 kPa\(^{-1}\) (Figure S21, Supporting Information), together
  with the detection limit of down to \lt{}10 Pa, comparable to the
  most sensitive resistive pressure sensor
  cite:Mannsfeld_2010,Pang_2012,Pan_2014,Zang_2015, with a
  considerably lower driving voltage that favors low-power-consumption
  designs. Following the design concept stated earlier, we point out
  that the major mechanism responsible for the current response is an
  increased contact area $\Delta A$ upon stress $\sigma$, and the
  change of penetration length $\Delta l$ (see Figure [[ref:fig:main-1]]b)
  is negligible within the stress range considered. Indeed, we model
  the contact radii at the top and bottom interfaces, $r_{\mathrm{t}}$
  and $r_{\mathrm{b}}$, as a function of $\varepsilon$ (details see
  Section S4, Supporting Information), which can describe the current response
  reasonably well (Figure S21, Supporting Information). The above
  analysis is further endorsed by the finite element method (FEM)
  simulations (Figure [[ref:fig:main-4]]d and Table S4, Supporting
  Information).  We further demonstrate the reversibility of current
  response by repeatedly applying and releasing a compressive stress
  of 204.2\(\pm\)12.3 Pa to our IFET device (Figure [[ref:fig:main-4]]e and Movie S3, Supporting Information). It is also noteworthy that the EGaIn
  sessile droplets function equally well on the NWs (Figure S18, Supporting Information), in spite of their sticky oxide surface.
  
  Finally, we discuss the transport properties of the NW/Gr
  interface. As illustrated earlier, since the carrier density at the
  interface is modulated by a partially-penetrated electrostatic field
  cite:Tian_2016,Shih2015Partially, it has been suggested that the
  current density can be described by the thermionic emission model
  cite:Sze2006Mosfets (details see Section S4 and Figure S25 in the
  Supporting Information), which allows to quantify the Schottky
  barrier height, $\Phi_{\mathrm{SB}}$, from the temperature-dependent
  measurements. We find that our IFET transfer current substantially
  increases with temperature (Figure [[ref:fig:main-5]]a). The scenario of
  temperature-induced increase of contact area or penetration length
  is excluded, since the thermal expansion of LM is small (\lt{}1%)
  within the temperature range considered here. Figure [[ref:fig:main-5]]b
  presents the experimentally-obtained current gain as a function of
  temperature, $G(T)=J_{\mathrm{DS}}(T)/J_{\mathrm{DS}}(T=20\ ^{\circ}
  \mathrm{C})$ at different $V_{\mathrm{G}}$ levels together with the
  least-square fitting curves using the thermionic emission
  model. Accordingly, at a more negative $V_{\mathrm{G}}$, the
  temperature dependence appears to be stronger, suggesting a higher
  $\Phi_{\mathrm{SB}}$ blocking thermally-induced transport of
  electrons. The extracted $\Phi_{\mathrm{SB}}$ values as a function
  of $V_{\mathrm{G}}$ is shown in Figure [[ref:fig:main-5]]c, spanning
  from 0.46 V at \(V_{\mathrm{G}}\)=-100 V to 0.16 V at
  \(V_{\mathrm{G}}\)=100 V.  The range of gate-tunable
  $\Phi_{\mathrm{SB}}$ is comparable to that of the Si/graphene
  heterojunction cite:Yang2012Barristor, but considerably lower than
  our theoretical prediction using the elementary electronic
  properties of graphene (Figure [[ref:fig:main-5]]c and Section S4,
  Supporting Information). A degree of Fermi level pinning due to the
  surface-bound traps cite:Meric_2008 may explain the observation.

 

* Summary                                                            :ignore:
:PROPERTIES:
:UNNUMBERED: t
:END:

In this work, we establish a new concept to reliably incorporate
mechanical durability and responsiveness in a transistor by
engineering the wettability of a semiconductor surface. Using the
superhydrophobic semiconductor NWs in an IFET, we systematically
analyze the origin of its ultrasoft elasticity driven by the
minimization of interfacial tension upon a compressive stress, as well
as the current response that can be modulated by gating through the
atomically-thin 2DEG. We believe that the fundamental understanding
and rational design strategy presented here can be utilized for a wide
range of ultrasensitive and stimuli-responsive nanoelectronics.

#   In this paper, we introduce a new electronic platform -- the
# interfacial field effect transistor (IFET), directly coupling
# mechanical response into a 2DEG-based vertical transistor using the
# reversible elastic response of conductive liquid on superhydrophobic
# semiconducting NWs. To demonstrate this concept, we design and
# fabricated an IFET using superhydrophobic F_{16}CuPc NWs grown on CVD
# graphene, with liquid metal droplet as the drain electrode. The
# droplet-based IFET shows ultra-low elastic modulus below 1kPa,
# superior to conventional elastic bulk materials, and enables sensitive
# stress sensing down to 10 Pa, sustaining a large strain. Multimodal
# current modulation of the IFET by electrostatic field and temperature
# with an excellent on/off ratio is further guaranteed by combining
# multiscale physical phenomena at the semiconductor interfaces. Our
# concept of IFET provides a facile approach of incorporating mechanical
# sensing into field effect transistors. We believe with enormous
# combinations of the 2DEG, semiconductor, and the conductive droplet,
# the field of application for IFET can be greatly extended, bringing
# opportunities including light detection, motion dection, full
# transparent and flexible sensors.




* Methods
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  Detailed descriptions of methods and characterization methods can be seen in the Supporting Information.

* Acknowledgments
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  T.T., N.A., R.S., and C.J.S. are grateful for the startup funding
  from ETH Z\uuml{}rich. T.T. acknowledges Dr. Tobias Keplinger for
  technical support of Raman microscopy. C.S.S. acknowledges Ms. Asel
  Maria Aguilar Sanchez from the Institute for Building Materials, ETH
  Zurich for her support of ESEM measurements. Y.T.L. and
  Y.C.C. acknowledge the Ministry of Science and Technology, Taiwan,
  for financial support (project no. MOST 105-2218-E-011-017-MY3).

* Competing Interests
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

  The authors declare that they have no competing financial interests.

* Author contributions
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  T.T. and C.J.S. conceived the concept and designed the
  experiments. T.T. and C.S.S. carried out the ESEM
  measurements. T.T., N.A. and R.S. fabricated and characterized the
  morphology and dynamic wetting properties of the F_{16}CuPc
  samples. Y.T. L. and Y.C. C. measured the GIXD spectroscopy of
  F_{16}CuPc samples. T.T. fabricated and tested the interfacial
  transistors. T.T. and M.V. designed the experiments using
  EGaIn. T.T. and C.J.S. developed the model for the stress-strain
  relation of droplets. T.T. and C.J.S. wrote the manuscript. All
  authors contributed to the discussion of the results and to the
  revision of the manuscript.



* References                                                         :ignore:
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

[[bibliography:ref.bib]]

\newpage{}

* Figures                                                            :ignore:

# #+CAPTION: *The concept of the interfacial field effect transistor (IFET)*. \textbf{a}, Schematic of the IFET (top) and its nanoscale structure (bottom), composed of a conductive liquid drain electrode (D), superhydrophic semiconducting NWs, a 2DEG source electrode (S) which is modulated by gate electrode (G). \textbf{b}, The elasticity of the conductive liquid at the superhydrophobic NW interface. When the height is compressed with $\Delta H$ (left), the contact radius increases by $\Delta x$ and the capillary length increases by $\Delta l$. When the external stress is released (right), the droplet returns to its original shape, enabled by the reversible motion on the hydrophobic NWs (small difference between $\theta_{\mathrm{adv}}^{*}$ and $\theta_{\mathrm{rec}}^{*}$).

#+CAPTION: Design concept of the proposed elastic interfacial transistor. (a), Schematic showing the device architecture at the micrometer (top) and nanometer (bottom) scales. Superhydrophobic semiconductor nanowires (NWs) are sandwiched between a conductive droplet at the CB state and a layer of 2DEG that allows partial penetration of an electrostatic field. (b), Upon applying an compressive stress $\sigma$ to the droplet, a vertical displacement $\Delta H$ advances the contact line by $\Delta x$, with an apparent advancing contact angle $\theta_{\mathrm{adv}}^{*}$. When the stress is released, the contact line moves back towards its equilibrium shape, with an apparent receding contact angel of $\theta_{\mathrm{rec}}^{*}$. At the nanometer scale,  may also result in an increase of penetration length $\Delta l$ that effectively reduces the transistor channel length.
#+ATTR_LATEX: :width 0.95\linewidth
#+NAME: fig:main-1
[[file:raw_img/scheme-1.pdf]]


# #+CAPTION: *Molecular orientation-induced superhydrophobicity of F_{16}CuPc*. \textbf{a},  Top-view (left) and cross-sectional (right) SEM images showing the morphology difference between F_{16}CuPc/SiO_{2} (green) and F_{16}CuPc NWs (cyan). Scale bars: 200 nm. \textbf{b}, GIXD spectra of F_{16}CuPc/SiO_{2} (left) and F_{16}CuPc NW (right) and corresponding 3D schematics of F_{16}CuPc orientation. The 4 major peaks (\alpha-\delta) were labeled in both the spectra and the corresponding diffraction planes. \textbf{c}, SEM (top) and Raman (bottom) images of F_{16}CuPc deposited onto a graphene sheet with a break, showing close relation between F_{16}CuPc morphology and orientation. Scale bar: 2 \(\mathrm{\mu}\)m. \textbf{d}, Water contact angles (large: ESEM, inset: sessile droplet) on F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc NW (bottom). Scale bars: 20 \(\mathrm{\mu}\)m. \textbf{e} Experimental and simulated dynamic water contact angles on  F_{16}CuPc/SiO_{2} (top) and  F_{16}CuPc NW (bottom) as functions of film thickness (NW height), showing the existence of Wenzel and CB states, respectively. \textbf{f}, Static contact angle of Hg droplet on F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc NW (bottom). \textbf{g}, Touching-removing cycles on F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc NW (bottom) using EGaIn, showing negligible adhesion of EGaIn on the NW surface compared with sticking on F_{16}CuPc/SiO_{2} Scale bar for \textbf{f} and \textbf{g}: 500 \(\mathrm{\mu}\)m..
#+CAPTION: Molecular orientation-induced superhydrophobicity in NWs. (a), Top-view (left) and cross-sectional (right) SEM micrographs showing the morphologies of F_{16}CuPc/SiO_{2} (green) and F_{16}CuPc NWs (cyan). Scale bar: 200 nm. (b), GIXD patterns and molecular orientation schematics of F_{16}CuPc/SiO_{2} (left) and F_{16}CuPc NWs (right), showing dominant edge-on (while circles) and face-on (black circles) orientations, respectively. The four representative planes (\alpha to \delta) are labeled accordingly. (c), SEM micrograph (top) and Raman mapping image (bottom) of F_{16}CuPc molecules deposited onto a graphene sheet with a break, clearly identifying the NW region. Scale bar: 2 \mu{}m. (d), Images of water sessile droplets sitting on F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc NWs (bottom) taken from the ESEM and CAG (inset) techniques. (e) CAG-determined water $\theta_{\mathrm{adv}}^{*}$, $\theta_{\mathrm{rec}}^{*}$, and $\theta_{\mathrm{s}}^{*}$ values (dots) with respect to the film thickness (NW height) for the F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc NW (bottom) samples, which are nicely described by the Wenzel and CB models (solid curves), respectively. (f), Mercury sessile droplets sitting on F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc NWs (bottom), showing $\theta_{\mathrm{s}}^{*}$ values of 147.7\(\pm\)2.5\(^{\circ}\)  and 157.1\(\pm\)3.8\(^{\circ}\), respectively. Scale bar: 500 \mu{}m. (g), Touching (left) - removing (right) of a suspended EGaIn droplet from F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc NWs (bottom) surfaces, showing non-stick characteristics of EGaIn to the NWs.
#+ATTR_LATEX: :width 0.9\linewidth
#+NAME: fig:main-2
[[file:img/scheme-2.pdf]]


# #+CAPTION: *The F_{16}CuPc/Gr IFET with LM as the drain electrode*. \textbf{a}, Schematic  of the device architecture. Insets: the simplified diagram (left) and the optical image of the LM droplet interface between the NW surface and the metal cantilever (right, scale bar: 500 \(\mathrm{\mu}\)m.). \textbf{b}, A typical $J_{\mathrm{DS}} - V_{\mathrm{G}}$ response curve of the IFET, with an on-off ratio of $3.9\times10^{4}$. Inset: histogram of the on-off ratios of fabricated  samples at \(V_{\mathrm{G}}\)=1 V. \textbf{c}, $J_{\mathrm{DS}} - V_{\mathrm{G}}$ curves of the IFET at different $V_{\mathrm{D}}$. \textbf{d}, Controlling the turn-on and turn-off of a commercial LED using the IFET. Left: schematic of the BJT amplifier circuit; middle: images of the IFET-LED circuit at the on and off states; right: the total current $I_{\mathrm{tot}}$ and $V_{\mathrm{G}}$ as functions of time for 10 cycles of on/off modulations.
#+CAPTION: Transport characteristics of the fabricated IFETs at zero strain. (a), Schematic of the device architecture, together with an optical micrograph taken by CAG. Scale bar: 500 \mu{}m. (b), A representative transfer curve at \(V_{\mathrm{D}}\) = 1 V, showing an on/off current ratio of 3.9\(\times{}\)10^{4}. The inset shows the histogram of the on/off current ratio extracted from \gt{}100 IFET devices. (c), Representative transfer curves at different drain voltages. (d), The schematic (left), photographs (middle), and output current $I_{\mathrm{tot}}$ (right) of an IFET-based circuit that controls the light intensity of a commercial LED with $V_{\mathrm{G}}$.
#+ATTR_LATEX: :width 0.95\linewidth
#+NAME: fig:main-3
[[file:img/scheme-3.pdf]]


# #+CAPTION: *Responsive elastic sensing using LM-based IFET*. \textbf{a}, Principle of the elastic stress-strain response of the LM droplet, showing the change of principal radii $R_{1}$ and $R_{2}$ upon stress. \textbf{b}, The stress-strain response of a \sim 0.1 \(\mathrm{\mu}\)L LM droplet from both experimental data and analytical model. Inset: elastic modulus as function of droplet volume, $V_{\mathrm{drop}}$ from the model. \textbf{c}, $I_{\mathrm{DS}}-V_{\mathrm{G}}$ curves of the IFET at various external stress levels. Insets: optical images of the LM under external stress (scale bars: 500 \(\mathrm{\mu}\)m.). \textbf{c}, Stress of the LM droplet calculated from both analytical model and FEM analysis, showing good agreement between the two methods. Scale bar: 200 \(\mathrm{\mu}\)m. \textbf{e} Increase of $I_{\mathrm{DS}}$ as function of time in a cycle compressing test of the IFET with average stress of 204.2\(\pm\)12.3 Pa, showing good reversibility. Scale bars: 100 \(\mathrm{\mu}\)m.
#+CAPTION: Elastic response of the proposed IFET. (a), Schematics of a droplet sandwiched between two plates before (top) and after (bottom) of a compressive stress, resulting a change of the principal radii, $R_{1}$ and $R_{2}$. (b), Compressive stress $\sigma$ as a function of strain $\varepsilon$ for a 0.1 \mu{}L mercury CB droplet obtained from experiments (dots) and our hydrostatic model (curve). Inset: model-predicted elastic modulus $E$ as a function of the droplet volume $V_{\mathrm{drop}}$. (c), Transfer curves under various compressive stress values. Insets: CAG images of the LM droplet under various external stress levels (scale bars: 500 \mu{}m.) (d), Comparison of CAG-captured (top) and finite-element simulated (bottom) droplet shape and stress values (Supplementary Table S4) under different degrees of compression. Scale bar: 200 \mu{}m. (e), Real-time monitoring of $I_{\mathrm{DS}}$ by repeatedly applying and releasing a compressive stress. 
#+ATTR_LATEX: :width 0.75\linewidth
#+NAME: fig:main-4
[[file:img/scheme-4.pdf]]


# #+CAPTION: *Thermal-current response of the IFET*. \textbf{a},  $J_{\mathrm{DS}}$ as a function of $V_{\mathrm{G}}$ at various temperature levels. \textbf{b}, Fitting of the gain of current ($I(T) / I(T=20\ ^{\circ} \mathrm{C})$) using the thermionic emission model. \textbf{c}, Schottky barrier heights extracted from the experimental temperature-dependent current gain data of the IFET from \textbf{c}, compared with the theoretical values. The gate voltage at graphene's charge neutral point, $V_{\mathrm{CNP}}$ is indicated by the vertical broken line.
#+CAPTION: Electron transport characteristics at the NW/Gr interface. (a), $J_{\mathrm{DS}}$ as a function of $V_{\mathrm{G}}$ at various temperatures, showing the thermoionic emission effect. (b), Experimentally-obtained (dots) and calculated (dashed curves) current gains, $G(T)$ , as a function of temperature $T$, suggesting that the thermoionic emission model can describe the interfacial current well. (c), Extracted Schottky barrier height $\Phi_{\mathrm{SB}}$ (blue dots) as a function $V_{\mathrm{G}}$. The dashed curve corresponds to our theoretical prediction using the elementary electronic properties of graphene, suggesting a degree of Fermi level pinning at the NW/Gr interface. 
#+ATTR_LATEX: :width 0.95\linewidth
#+NAME: fig:main-5
[[file:img/scheme-5.pdf]]



