#+LATEX_CLASS: revtex4-1
#+LATEX_CLASS_OPTIONS: [prb, onecolumn, linenumbers, hyperref, superscriptaddress, preprint, amsmath, amssymb, noshowpacs]
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{times}
#+LATEX_HEADER: \newenvironment{boldabstract}{\setlength{\parindent}{0in}\setlength{\parskip}{0in}\bfseries}{\par\vspace{-6pt}}

#+OPTIONS: tex:t toc:nil todo:t author:nil date:nil title:nil ^:t tags:nil
#+DESCRIPTION:

#+NAME: latex-author-list
#+BEGIN_EXPORT latex
% The author list
\title{An elastic interfacial transistor enabled by superhydrophobicity}
\author{Tian Tian}
\affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir-Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}
\author{Chander Shekhar Sharma}
\affiliation{Institut of Energy Technology, ETH Z{\"{u}}rich, Sonneggstrasse 3, CH-8092 Z{\"{u}}rich, Switzerland}
\affiliation{Department of Mechanical Engineering, Indian Institute of Technology Ropar, Rupnagar, Punjab 140001, India}
\author{Navanshu Ahuja}
\affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir-Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}
\author{Matija Varga}
\affiliation{Electronics Laboratory, ETH Z{\"{u}}rich,  Gloriastrasse 35,  CH-8092 Z{\"{u}}rich, Switzerland}
\author{Raja Selvakumar}
\affiliation{Department of Chemical and Biomolecular Engineering, University of California, Berkeley, CA 94720, USA}
% \affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir-Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}
\author{Yen-Ting Lee}
\affiliation{Department of Chemical Engineering, National Taiwan University of Science and Technology, Taipei 10607, Taiwan.}
\affiliation{National Synchrotron Radiation Research Center, Hsinchu 30076, Taiwan.}
\author{Yu-Cheng Chiu}
\affiliation{Department of Chemical Engineering, National Taiwan University of Science and Technology, Taipei 10607, Taiwan.}
\author{Chih-Jen Shih}
\email{Correspondence should be addressed to C.-J.S. chih-jen.shih@chem.ethz.ch}
\affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir-Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}
#+END_EXPORT

#+LaTeX: \maketitle

  
* Abstract
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
Recent advances in semiconductor materials and physics have driven the
development of field-effect transistors (FETs) for a variety of
applications cite:Torsi_2013_rev,Ben_Sasson_2014.  Enabling mechanical
durability and responsiveness in FETs offers new technological
opportunities beyond the reach of existing platforms
cite:Someya_2004,Oh_2016.  It is desirable to intrinsically
incorporate the responsiveness in semiconductor by rational material
design cite:Oh_2016 but may often compromise the device performance
and processability cite:Lee_2018. For example, the elasticity, the
ability of a soft material to return to its original shape when the
deforming stress is released, requires an entropic force acting within
the material, fundamentally impeding carrier transport in a solid
material cite:OConnor_2011_strain_P3HT.  Here we present a
conceptually different approach concept to address the challenge,
inspired by the liquid-repellent behavior of a sessile droplet
interacting with a superhydrophobic surface. We design an interfacial
field effect transistor (IFET) made by superhydrophobic semiconductor
nanowires (NWs) sandwiched between a layer of two-dimensional electron
gas (2DEG) and a conductive Cassie-Baxter (CB) sessile
droplet. Following the hydrostatic deformation of the CB droplet upon
mechanical stress, we report an extremely small elastic modulus of 820
pascal vertical to the substrate plane, or \sim{}100 times softer then
Ecoflex rubbers, enabling an excellent stress detection limit down to
<10 pascal. The IFET has an on/off current ratio exceeding
3\(\times\)10^{4}, as the carrier density profile at the NW/2DEG
interface is modulated by partially-penetrated electrostatic
field. This study demonstrates a versatile platform that bridges
multiple macroscopic interfacial phenomena with nanoelectronic
responses.

* Main
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

Figure [[ref:fig:main-1]] presents the device architecture of the proposed
IFET. We consider a quantum capacitor device cite:Luryi_1988, in which
a semiconductor layer is sandwiched between a conductive drain (D) and
a 2DEG source (S) electrodes. The ultrathin and
low-quantum-capacitance (low $C_{\mathrm{Q}}$) nature of 2DEG allows
partial penetration of an electrostatic field exerted by the
underlying gate (G) electrode cite:Shih2015Partially,Tian_2016,
modulating the carrier density in semiconductor that controls
drain-to-source current (\(I_{\mathrm{DS}}\)) (Figure
[[ref:fig:main-1]](a)).  In addition, the fact that $I_{\mathrm{DS}}$
passes through two semiconductor-electrode interfaces maximizes the
response to the interfacial properties.

Next, we sought to grow semiconductor NWs directly on the 2DEG,
forming a superhydrophobic surface at the Cassie-Baxter (CB) state
cite:Cassie_1944. A conductive sessile droplet is then placed on top
of the NWs, acting as the D electrode, with the radius of contact
$R$. Accordingly, applying a compressive stress $\varepsilon$ on top
of the sessile leads to an horizontal elastic displacement $\Delta x$
that advances the contact line, with an apparent advancing contact
angle $\theta_{\mathrm{adv}}^{*}$ (Figure [[ref:fig:main-1]](b)
left). When the stress is released, the contact line moves back
towards its equilibrium shape, with an apparent receding contact angel
of $\theta_{\mathrm{rec}}^{*}$ (Figure [[ref:fig:main-1]](b) right),
enabling the reversibility. We hypothesized that the electrical
response during the process results from: (i) an increase of the
droplet contact area $\Delta A \approx 2 \pi R \Delta x$ at the
macroscopic level and (ii) an increase of capillary length $\Delta l
\approx \epsilon r^{2}/2\gamma_{\mathrm{L}}$ that effectively reduces
the semiconductor channel length in the NWs (see Figure
[[ref:fig:main-1]](b) bottom), where $\gamma_{\mathrm{L}}$ is the surface
tension of liquid and $r$ is the average radius between NWs.  In order
to realize the concept, monolayer graphene (Gr), a 2DEG material with
the smallest quantum capacitance near the Dirac point cite:Tian_2016,
is used. As for the semiconductor material, it is well-known that the
covalently bonded semiconductors generally possess a high surface
energy, owing to the high surface polarity cite:Azimi_2013_wetting_RO and
dangling bonds cite:Zhang_2004_dangling, presumably leading to the
Wenzel state. To this end, the organic semiconductor solids containing
the \(\pi\)-conjugated molecules, with the molecular polarizability
considerably reduced by perfluoration, were considered. We have
managed to grow NWs of Copper(II) hexadecafluorophthalocyanine
(F_{16}CuPc), a n-type organic semiconductor with high air stability
cite:Bao_1998, on a sheet of monolayer graphene transferred onto a
SiO2/Si substrate (details see Supplementary Information), as shown in
Figure [[ref:fig:main-2]](a).

The F_{16}CuPc NWs have high aspect ratios, with diameters and heights
of 30 - 60 and several hundred nanometers, respectively. We note that
the NW morphology is similar to that of F_{16}CuPc templated by
perylene-3,4,9,10-tetracarboxylic-3,4,9,10-dianhydride (PTCDA)
cite:Yang_2009_F16_PTCDA or gold nanoparticles
cite:Mbenkum_2006_F16_1D, presumably sharing the same growth
mechanism. Indeed, the strong $\pi-\pi$ interactions between graphene
and F_{16}CuPc basal planes lower the critical free energy of
heterogeneous nucleation; in combination with the weak van der Waals
(vdW) interactions between the perfluorinated molecular edges that
limit the lateral growth, it explains why the NW structure is
thermodynamically favored. The structural driving force resulting from
the subtle asymmetry between in-plane and out-of-plane interactions,
however, disappears when the substrate-molecule interactions are not
sufficiently strong cite:Tian_2017, as observed in the thin-film
structure grown on bare SiO2 (Figure [[ref:fig:main-2]](a)).

Figure [[ref:fig:main-2]](b) shows the grazing incidence X-ray diffraction
(GIXD) patterns for the F_{16}CuPc NW and F_{16}CuPc/SiO_{2}
samples. The F_{16}CuPc/SiO_{2} sample has an intense peak along the
$q_{\mathrm{z}}$ axis, labeled as $\alpha$ (/d/-spacing = 1.470
nm). It corresponds to the (002) plane in the F_{16}CuPc single crystal
cite:Yang_2009_F16_PTCDA that is perpendicular to the substrate normal
vector, suggesting a dominant “edge-on” orientation
(Fig. [[ref:fig:main-2]](b) left). It is also endorsed by the position of
the (\(\bar{1}\)22) plane peak near the $q_{\mathrm{xy}}$ axis
(\(\beta\)) cite:Yoon_2010_crystal_F16, with a /d/-spacing of 0.305
nm. On the other hand, for the F_{16}CuPc NW sample, we observe
an additional peak corresponding to the (002) plane (labeled as
$\gamma$) (Figure [[ref:fig:main-2]](b) right), with its wave vector
rotated by $\sim 76^{\circ}$ with respect to the $q_{\mathrm{z}}$
axis and a /d/-spacing of 1.440 nm, slightly smaller than that in
the edge-on orientation. Together with the (\(\bar{1}\)22) peak
located at the $q_{\mathrm{z}}$ axis, we point out the emergence of
the “face-on” phase in the NWs. The predominant face-on orientation
in the n-type NWs facilitates electron transport perpendicular to the
substrate, through the intermolecular $\pi-\pi$ interactions. The
substrate-induced orientation transition also results in the
angle-dependent scattering of the Davydov multiplets that alters the
Raman characteristics cite:Cerdeira_2013_RamanF16(details see
Supplementary Information). Figure [[ref:fig:main-2]](c) presents both the
scanning electron microscopy (SEM) and Raman map using 532 nm laser
for the intensity ratio of the peak at 1380 cm^{-1} to that at 1315
cm^{-1}, I(1380)/I(1315), on the F_{16}CuPc film deposited on a sheet of
SiO_{2}-supported graphene with a break. The NW region, with a higher
I(1380)/I(1315) ratio, is clearly identified.

We examined the wettability of the two F_{16}CuPc samples (Figures
[[ref:fig:main-2]](d)-[[ref:fig:main-2]](g)). The apparent static contact
angles (\(\theta_{\mathrm{s}}^{*}\)) of water were independently
determined by (i) contact angle goniometer (CAG) and (ii) condensation
of supersaturated water vapor in an environmental scanning electron
microscope (ESEM) setup. For example, Figure [[ref:fig:main-2]](d)
presents the CAG/ESEM-measured $\theta_{\mathrm{s}}^{*}$ of a 50 nm
F_{16}CuPc/SiO_{2} and a 300 nm F_{16}CuPc NW samples, showing
103.0\(\pm\)5.4\(^{\circ}\) / 107.0\(\pm\)3.9\(^{\circ}\) and
152.8\(\pm\)3.9\(^{\circ}\) / 149.8\(\pm\)3.4\(^{\circ}\),
respectively. To gain more insights into the superhydrophobic states
of the two surfaces, we conducted a series of static and dynamic
contact angle measurements which allow us to determine
$\theta_{\mathrm{adv}}^{*}$, $\theta_{\mathrm{rec}}^{*}$ and
$\theta_{\mathrm{s}}^{*}$, with respect to the film thickness (Figure
[[ref:fig:main-2]](e)). The apparent contact angle values
$\theta_{\mathrm{i}}^{*}$, where i=adv, rec, and s, were numerically
fitted by the Wenzel (W) cite:Wenzel_1936 and CB cite:Cassie_1944
models:

\begin{eqnarray}
\label{eq:2}
&\cos \theta^{*}_{\mathrm{i,W}} =& r_{\mathrm{W}} \cos \theta_{\mathrm{i}} \\
&\cos \theta^{*}_{\mathrm{i,CB}} =& r_{\mathrm{CB}} f \cos \theta_{\mathrm{i}} + f - 1
\end{eqnarray}

 where $r_{\mathrm{W}}$ and $r_{\mathrm{CB}}$ are the roughness ratio
 of the wet surface area in the two (W and CB) states,
 $\theta_{\mathrm{i}}$ is the respective contact angles on an ideally
 flat surface and $f$ is the fraction of solid surface area wet by
 water in the CB model. By assuming $r_{\mathrm{W}} \approx
 r_{\mathrm{CB}}$ owing to the intrinsically identical chemical nature
 of the two surfaces, we find that the water wettability on
 F_{16}CuPc/SiO_{2} and F_{16}CuPc NW samples can be nicely described
 by the Wenzel and CB models, respectively, allowing us to determine
 $\theta_{\mathrm{adv}}$=107\(^{\circ}\),
 $\theta_{\mathrm{rec}}$=78\(^{\circ}\),
 $\theta_{\mathrm{s}}$=94\(^{\circ}\), and $f=0.093$ (for 300 nm
 NW). We point out that the graphene-induced molecular orientation
 effects have eventually led to the transition between Wenzel and CB
 surface states, which to our knowledge has never been demonstrated in
 molecular solids.
 
 We next illustrate the wettability of conductive sessile droplets,
 specifically the liquid metals (LM) at room temperature on the
 F_{16}CuPc samples. It is noteworthy that the key challenge hindering
 the development of LM-based devices is the undesirable adhesion of LM
 to the device surface, in particular with the eutectic gallium indium
 (EGaIn), in which the formation of gallium oxide layer effectively
 reduces the interfacial tension
 cite:Dickey_2008,Doudrick_2014_oxide. Mercury sessile droplets
 sitting on the F_{16}CuPc/SiO_{2} and F_{16}CuPc NW surfaces show
 $\theta_{\mathrm{s}}^{*}$ values of 147.7\(\pm\)2.5\(^{\circ}\) and
 157.1\(\pm\)3.8\(^{\circ}\), respectively(Figure [[ref:fig:main-2]](f)).
 Regarding the EGaIn sessile droplets, although the
 $\theta_{\mathrm{s}}^{*}$ values of fresh droplets are close on both
 surfaces, interestingly, the adhesive property is different, as
 revealed in Figure [[ref:fig:main-2]](g). We suspended an EGaIn droplet
 using a microcapillary, followed by repeatedly touching/removing the
 droplet from the two surfaces. We found that the EGaIn droplet can be
 easily detached from the F_{16}CuPc NW surface, compared to the stuck
 of droplet to the F_{16}CuPc/SiO_{2} surface. The observations was
 further corroborated by their apparent sliding angles
 $\theta_{\mathrm{sl}}^{*}$, equivalent to the degree of contact angle
 hysteresis of 56.1\(\pm\)13.2\(^{\circ}\) and
 14.6\(\pm\)2.6\(^{\circ}\) on F_{16}CuPc/SiO_{2} and F_{16}CuPc NW
 samples, respectively. Accordingly, the excellent CB characteristics
 of LM sessile droplets on the semiconducting NWs form a solid basis
 for the proposed elastic IFET.

 Figure [[ref:fig:main-3]](a) presents the schematic of the proposed
 elastic IFET. A sheet of monolayer graphene grown by chemical vapor
 deposition (CVD) was transferred onto a 300 nm SiO_{2}/Si substrate
 functionalized by octadecyltrichrolosilane self-assembled monolayer
 (OTS SAM) cite:Yan_2011, in order to minimize the substrate-induced
 traps cite:Wang_2011.  The lateral graphene FET has an on/off current
 ratio of \sim{}10 and a field-effect mobility (\(\mu_{\mathrm{FE}}\))
 of \sim2000 cm^{2}V^{-1}s^{-1} at room temperature, with the charge
 neutrality point (CNP) at the gate voltage of \sim0 V (Figure
 S14). Subsequently, a layer of \sim300 nm-high F_{16}CuPc NWs were
 deposited on graphene, followed by placing a cantilever-attached LM
 droplet on top as the D electrode (details see Supplementary
 Information).  The current density $J_{\mathrm{DS}}$ from the LM (D)
 to graphene (S) in the IFET was then quantified by normalizing the
 drain current by the contact area of the sessile droplet with the NW
 layer, as a function of drain and gate voltages ($V_{\mathrm{D}}$ and
 $V_{\mathrm{G}}$). Note that since the NWs are only partially wetted,
 the actual current density passing through individual NWs is
 estimated to be $J_{\mathrm{DS}}/f$. The carrier density in
 F_{16}CuPc molecules adjacent to the NW/graphene interface is
 modulated by the partially penetrated field effect through monolayer
 graphene cite:Tian_2016,Shih2015Partially, modulating the Schottcky
 barrier height at the interface cite:Yang2012Barristor. The face-on
 orientation of the F_{16}CuPc molecules not only facilitates carrier
 transport along the NWs, but also aligns the work functions of
 graphene and F_{16}CuPc at the interface
 cite:Mao_2010_F16_level_orien,Ren_2011_F16Gr_Elevel. The transfer
 curve for a representative IFET at $V_{\mathrm{D}}$= 1 V demonstrates
 an on/off current ratio of 3.9\(\times\)10^{4} (Figure
 [[ref:fig:main-3]](b)), in line with the state-of-the-art vertical
 field-effect transistor (VFET) technology
 cite:Yang2012Barristor,Shih2015Partially,Sun_2017_COF_VFET,Ben_Sasson_2011. Moreover,
 the fact that the present IFET is well-functional at a low
 $V_{\mathrm{D}}$ reflects it potential towards the low-power
 electronics design, which remains challenging for most resistive
 force-sensing components cite:Pan_2014,Pang_2012. A number of IFET
 samples were characterized, showing an average on/off current ratio
 of 5\(\times\)10^{3} at $V_{\mathrm{D}}$=1 V (Figure
 [[ref:fig:main-3]](b) inset). The transfer curves at different
 $V_{\mathrm{D}}$ are shown in Figure [[ref:fig:main-3]](c), with the
 on/off current ratio gradually decreases with $V_{\mathrm{D}}$, owing
 to a mechanism analogous to the drain-induced barrier lowering (DIBL)
 effect in short-channel FETs cite:Lundstrom_2003. More
 discussions about the transport mechanisms, together with the band
 diagrams, are stated in Supplementary Information. We further
 demonstrate an application concerning the gate-tunability of the
 F_{16}CuPc NW IFET, by switching an commercial green LED (Figure
 [[ref:fig:main-3]](d)) with the help of a home-made bipolar junction
 transistor (BJT) amplifier circuit.  We demonstrate that over 10
 cycles of on-off switching cycles by tuning the $V_{\mathrm{G}}$ from
 -75 V to 100 V, the total current through the circuit can be tuned by
 250 folds with appreciable stability, showing good and reliable gate
 tunability.
  
  The elasticity of liquid enables response to pressure stimuli at the
  NW/LM interface, with relatively large displacement compared with
  conventional piezoelectric devices. The curvature at the liquid-air
  interface creates a curvature pressure $p$, described by the
  Young-Laplace equation: \(p = \gamma_{\mathrm{L}} (R_{1}^{-1} +
  R_{2}^{-1})\), where $R_{1}$ and $R_{2}$ are the principle radii of
  the LM droplet, and $\gamma_{\mathrm{L}}$ is the surface tension of
  the liquid. When compressed between two parallel plates, the droplet
  undergoes an uniaxial strain $\sigma = \Delta H / H_{0}$, where
  $\Delta H$ and $H_{0}$ are the change of droplet height and droplet
  height without strain, respectively. The strain changes the
  curvature, and in turn gives rise to a stress
  $\varepsilon=p(H_{0}-\Delta H) - p(H_{0})$ (Figure
  [[ref:fig:main-4]](a)). The strain-stress relation of the droplet
  resembles the elasticity in soft materials, and is the key principle
  behind the elastic IFET. Since the gravitational effect can be
  ignored for sub-microlitre LM droplets (Bond number much less than
  1), the boundaries of the droplet is spherical and an analytical
  model is used to solve the stress-strain relation (details see
  Supplementary Information). The value of $H_{0}$ is determined by the
  volume of droplet $V_{\mathrm{drop}}$, and contact angles at the top
  and bottom plate ($\theta_{\mathrm{t}}$ and $\theta_{\mathrm{b}}$)
  as:
  \begin{equation}
  \label{eq:5}
  \begin{aligned}
    H_{0} &= \sqrt[3]{\frac{3 V_{\mathrm{drop}}}{4 \pi}} \sqrt[3]{\frac{1}{ 
   g(\theta_{\mathrm{t}}) + g(\theta_{\mathrm{b}}) -1 }}  \left(\cos \theta_{\mathrm{t}} + \cos \theta_{\mathrm{b}}\right) \\
    g(\theta) &= \left(\frac{1 + \cos \theta}{2} \right)^{2} \left(2 - \cos \theta \right)
  \end{aligned}
  \end{equation}
 Figure [[ref:fig:main-4]](b) shows the experimental and simulated elastic
  stress of a \sim0.1 \mu{}L Hg droplet as a function of vertical
  strain up to 13.5%. Under low strain, the stress-strain relation is
  close to linearity, giving an elastic modulus $E=\partial \varepsilon
  / \partial \sigma$ of \sim{}820 Pa. Such elastic modulus of a
  compressed droplet stems from the superhydrophobicity of NWs and the
  surface tension of LM, and is effectively identical to the
  conventional elastic (Young's) modulus of bulk materials when
  concerning the application of elastic sensing. We note that the
  elastic modulus of LM droplet is essentially lower than conventional
  elastic polymer, for instance, Polydimethylsiloxane (PDMS, \sim250
  kPa cite:Loetters_1997), and even the state-of-art low modulus soft
  materials (several kPa) cite:Jang_2015, indicating the huge
  potential in elastic sensing. More interestingly, our model shows
  that the elastic modulus deceases with the volume of the droplet
  $V_{\mathrm{drop}}$ (Figure [[ref:fig:main-4]](b) inset), allowing
  facile tuning of the modulus. We measure the response of
  $I_{\mathrm{DS}}$ to the stress at different $V_{\mathrm{G}}$
  levels, as shown in Figure [[ref:fig:main-4]](c). $I_{\mathrm{DS}}$
  increases with $\sigma$ with almost no dependency on
  $V_{\mathrm{G}}$, while the current on/off modulation is not
  affected by elastic stress. The sensitivity of the elastic electric
  response $\eta = (I/I_{0} - 1)/\varepsilon$, where $I$ and $I_{0}$
  are the $I_{\mathrm{DS}}$ with and without stress, is determined to
  be 0.036 Pa^{-1}. The stress can thus be detected at a extreme low
  level (less than 10 Pa) with measurable $I_{\mathrm{DS}}$ change,
  comparable with the most sensitive elastic sensing approaches
  cite:Pang_2012,Pan_2014. As we propose in the introduction, two
  mechanisms may be responsible for the current increase upon elastic
  stimuli, i.e. the change of LM/NW contact area, and increase of LM
  capillary length. When the LM droplets are operated within the CB
  state, with an $\varepsilon$ of \sim{}100 Pa and average spacing
  between the NWs of \sim{}50 nm, the change of capillary length is
  negligible. Indeed the $I_{\mathrm{DS}}$ amplification ratio
  predicted from our theoretical model is close to the experimental
  values (Figure S24), indicating that the change of contact area is
  the main cause of the current response. We ascribe the discrepancy
  between the experimental data and our model to the possible
  penetration of LM into microscale defects on the graphene sheet,
  where wetting state at the NW/LM interface turns from CB state to
  Wenzel state, which is known to occur at a pressure \gt{}250 Pa on a
  superhydrophobic surface cite:Lafuma_2003, and can be observed in
  the defect areas of the NW film (Figure S17).  In order to validate
  our analytical model, we use finite element method (FEM) to analyze
  the stress distribution in the droplet using the experimental
  droplet geometry. As shown in Figure [[ref:eq:4]](d), the stress
  calculated from the analytical model and FEM are of good
  agreement. Finally, we examine the reversibility of the pressure
  sensing using elastic LM droplets. We monitored the change of the
  drain-source current as a function of time during more than 10
  cycles of pressing-releasing of the LM droplet (Figure
  [[ref:fig:main-4]](e)). At average stress of 204.2\(\pm\)12.3 Pa, the
  current can be tuned over 12 to 14 folds. Moreover the low pressure
  current $I_{0}$ is maintained closed to the initial value,
  indicating reversibility of the superhydrophobic-enabled elastic
  sensing.

  The Schottky transport barrier at the NW/Gr interface also
  incorporates thermal response into the IFET. Since
  the gate-tunable current modulation is related to the Schottky
  barrier height $\Phi_{\mathrm{SB}}$, the current density flowing
  through the interface can be described by the thermionic emission
  equation cite:Sze2006Mosfets:

  \begin{equation}
  \label{eq:4}
  J_{\mathrm{DS}} = A^{**} T^{2} \exp(- \frac{e \Phi_{\mathrm{SB}}}{kT}) 
		  \left[ \exp(\frac{e V_{\mathrm{D}}}{kT}) - 1\right]
  \end{equation}
  where $T$ is the temperature, $A^{**}$ is the reduced effective
  Richardson constant, $e$ is the unit charge and $k$ is the Boltzmann
  constant. At same $V_{\mathrm{D}}$ and $\Phi_{\mathrm{SB}}$, the
  $J_{\mathrm{DS}}$ is solely controlled by $T$. Within the reverse
  bias regime, where Schottky barrier dominates the current, the
  higher $\Phi_{\mathrm{SB}}$ is, the greater $J_{\mathrm{DS}}$ can be
  tuned by temperature. Note that since the thermal volume expansion
  of LM is relatively small (\sim{}1% from 20 $^{\circ} \mathrm{C}$ to
  100 $^{\circ} \mathrm{C}$), the temperature-induced change of
  contact area and capillary length can be ignored. We tested the
  gated-tuned $J_{\mathrm{DS}}$ with the temperature ranging from 20
  $^{\circ} \mathrm{C}$ to 100 $^{\circ} \mathrm{C}$, as shown in
  Figure [[ref:fig:main-5]](a). As expected, $J_{\mathrm{DS}}$ increases
  with the rise of temperature, due to the dominance of $T^{2}$ in
  Eq. [[ref:eq:4]]. The current on-off modulation by $V_{\mathrm{G}}$ is
  not affected, confirming that temperature and gate control are
  independent. To further investigate the influence of temperature on
  the current, we measured the gain of current
  $G(T)=J_{\mathrm{DS}}(T)/J_{\mathrm{DS}}(T=20\ ^{\circ} \mathrm{C})$
  at different $V_{\mathrm{G}}$ levels ([[ref:fig:main-5]](c)). We observe
  a higher current gain at more negative $V_{\mathrm{G}}$, indicating
  the increase of Schottky barrier. To estimate the
  $\Phi_{\mathrm{SB}}$ at each $V_{\mathrm{G}}$ level, we fitted the
  $G(T)$ curves using least square regression by equation
  [[ref:eq:4]]. The fitted $G(T)$ curves show close resemblance to the
  experimental data, proving the therionic emissive nature of the
  temperature-dependent current gain in our interfacial transistor. We
  further plot the extracted $\Phi_{\mathrm{SB}}$ values as a function
  of $V_{\mathrm{G}}$ in Figure [[ref:fig:main-5]](d). The Schottky
  barrier height reduces from 0.46 V at \(V_{\mathrm{G}}\)=-100 V to
  0.16 V at \(V_{\mathrm{G}}\)=100 V, with a tuning range of 0.30 V,
  consistent with other reports of graphene-based VFETs
  cite:Yang2012Barristor,Dankert_2017_graphene_spin_SB. We also
  calculate the theoretical tuning range of $\Phi_{\mathrm{SB}}$
  cite:Tian_2016, with the CNP gate voltage $V_{\mathrm{CNP}}$ taken
  from graphene conductivity tests (details see Supplementary
  Information) and the $\Phi_{\mathrm{SB}}$ value at graphene's CNP as
  0.32 V cite:Ren_2011_F16Gr_Elevel, giving a tuning range up to 0.59
  V. The discrepancy between our experimental data and theoretical
  value may be explained by the pinning of graphene's Fermi level by
  surface-bound traps cite:Meric_2008.

* Summary
:PROPERTIES:
:UNNUMBERED: t
:END:
  In this paper, we introduce a new electronic platform -- the
interfacial field effect transistor (IFET), directly coupling
mechanical response into a 2DEG-based vertical transistor using the
reversible elastic response of conductive liquid on superhydrophobic
semiconducting NWs. To demonstrate this concept, we design and
fabricated an IFET using superhydrophobic F_{16}CuPc NWs grown on CVD
graphene, with liquid metal droplet as the drain electrode. The
droplet-based IFET shows ultra-low elastic modulus below 1kPa,
superior to conventional elastic bulk materials, and enables sensitive
stress sensing down to 10 Pa, sustaining a large strain. Multimodal
current modulation of the IFET by electrostatic field and temperature
with an excellent on/off ratio is further guaranteed by combining
multiscale physical phenomena at the semiconductor interfaces. Our
concept of IFET provides a facile approach of incorporating mechanical
sensing into field effect transistors. We believe with enormous
combinations of the 2DEG, semiconductor, and the conductive droplet,
the field of application for IFET can be greatly extended, bringing
opportunities including light detection, motion dection, full
transparent and flexible sensors.




* Methods
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  Detailed descriptions of methods and characterization methods can be seen in the Supplementary Information.

* Acknowledgments
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  T.T., N.A., R.S., and C.-J.S. thank the ETH starup
  funding. T.T. thank Dr. Tobias Keplinger and Wang Yaru for
  assistance with Raman microscopy.
*************** TODO Complete the acknowledgments
*************** END


* Competing Interests
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

  The authors declare that they have no competing financial interests.

* Author contributions
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  T.T. and C.-J. S. conceived the concept, designed the experiments
  and co-write the manuscript. T.T. and C.S.S. carried out the ESEM
  measurements. T.T., N.A. and R.S. fabricated and characterized the
  morphology and dynamic wetting properties of the F_{16}CuPc/Gr
  samples. Y.-T. L. and Y.-C. C. measured the GIXD
  spectroscopy. T.T. fabricated and tested the interfacial
  transistors. T.T. and M.V. designed the experiments using EGaIn. All
  authors contributed to the discussion of the results and to the
  revision of the manuscript.



* References
  :PROPERTIES:
  :UNNUMBERED: t
  :END:


[[bibliographystyle:naturemag]]
[[bibliography:ref.bib]]

\newpage{}

#+CAPTION: The concept of an elastic interfacial transistor. (a) Schematic of the interfacial transistor (top) and its nanoscale structure (bottom), composed of a conductive liquid drain electrode, superhydrophic semiconducting NWs, a 2DEG source electrod which is modulated by dielectrics-gate terminal. (b) The elasticity of the conductive liquid at the NW interface. When the height is compressed with $\Delta H$ (left), the contact radius increases by $\Delta x$ and the capillary length increases by $\Delta l$. When the external stress is released (right), the droplet returns to its original shape, enabled by the reversible motion on the hydrophobic NWs (small difference between $\theta_{\mathrm{adv}}^{*}$ and $\theta_{\mathrm{rec}}^{*}$).
#+ATTR_LATEX: :width 0.95\linewidth
#+NAME: fig:main-1
[[file:img/scheme-1.pdf]]


#+CAPTION: Molecular orientation-induced superhydrophobicity. (a)  Top-view and cross-sectional SEM images showing the morphology distinction between F_{16}CuPc/SiO_{2} (thin film, green) and F_{16}CuPc/Gr (NWs, cyan). Scale bars: 200 nm. (b) GIXD spectra of F_{16}CuPc/SiO_{2} (left) and F_{16}CuPc/Gr (right) and corresponding 3D schemes of F_{16}CuPc orientaion. The 4 major peaks (\alpha-\delta) were labeled in both the spectra and the corresponding diffraction planes in the schemes. (c) SEM (top) and Raman (bottom) images of F_{16}CuPc deposited onto a graphene sheet with a break, showing close relation between F_{16}CuPc morphology and orientation. (d) Water contact angles (large: ESEM, inset: sessile droplet) on F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc/Gr (bottom). (e) Experimental and simulated dynamic water contact angles on  F_{16}CuPc/SiO_{2} (top) and  F_{16}CuPc/Gr (bottom) as functions of film thickness (NW height), showing the existence of Wenzel and CB states, respectively. (f) Static contact angle of Hg droplet on F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc/Gr (bottom). (g) Attach-detach cycle test on F_{16}CuPc/SiO_{2} (top) and F_{16}CuPc/Gr (bottom) using EGaIn, showing negligible adhesion of EGaIn with the NW.
#+ATTR_LATEX: :width 0.95\linewidth
#+NAME: fig:main-2
[[file:img/scheme-2.pdf]]


#+CAPTION: The F_{16}CuPc/Gr IFET with LM as the drain electrode. (a) Schematic illustration of the device architecture. The simplified diagram and an optical image of the semiconductor-LM interface are shown in the insets. (b) A typical $J_{\mathrm{DS}} - V_{\mathrm{G}}$ response curve of the IFET, with an on-off ratio of $3.9\times10^{4}$. Inset: histogram of the on-off ratios of fabricated  samples. (c) $J_{\mathrm{DS}} - V_{\mathrm{G}}$ curves of the IFET under different $V_{\mathrm{D}}$ levels. (d) Controlling the turn-on and turn-off of a commercial LED using the IFET. Left: scheme of the circuit; middle: images of the IFET-LED circuit in the on and off states; right: the total current $I_{\mathrm{tot}}$ and $V_{\mathrm{G}}$ as functions of time for 10 cycles of on/off modulations.
#+ATTR_LATEX: :width 0.95\linewidth
#+NAME: fig:main-3
[[file:img/scheme-3.pdf]]


#+CAPTION: Responsive elastic sensing using LM-based IFET. (a) Principle of the elastic stress-strain response of the LM droplet. (b) The stress-strain response of a \sim 0.1 \(\mathrm{\mu}\)L LM droplet from both experimental data and analytical model. Inset: elastic modulus as function of droplet volume, $V_{\mathrm{drop}}$ from the model. (c) $I_{\mathrm{DS}}-V_{\mathrm{G}}$ curves of the IFET under various external stress levels. Insets: optical images of the LM under external stress. (c) Stress of the LM droplet calculated from both analytical model and FEM analysis, showing good agreement between the two methods. (e) Increase of $I_{\mathrm{DS}}$ as function of time in a cycle compressing test of the IFET with average stress of 204.2 $\pm$ 12.3 Pa, showing good reversibility.
#+ATTR_LATEX: :width 0.8\linewidth
#+NAME: fig:main-4
[[file:img/scheme-4.pdf]]


#+CAPTION: Thermal-current response of the IFET. (a)  $J_{\mathrm{DS}}$ as a function of $V_{\mathrm{G}}$ at various temperature levels. (b) Fitting of the gain of current ($I(T) / I(T=20\ ^{\circ} \mathrm{C})$) using the thermionic emission model. (c) Schottky barrier heights extracted from the experimental temperature-dependent current gain data of the IFET from (c), compared with the theoretical values. The gate voltage at graphene's charge neutral point, $V_{\mathrm{CNP}}$ is determined as 18 V in gate-tunable graphene conductivity measurements, and the Schottky barrier height at CNP is taken as 0.32 eV from Ref. citenum:Ren_2011_F16Gr_Elevel.
#+ATTR_LATEX: :width 0.95\linewidth
#+NAME: fig:main-5
[[file:img/scheme-5.pdf]]






